services:
  redis:
    image: redis:7.2-bookworm  # You can use any version, 7.2-bookworm is used as an example
    container_name: redis_server
    ports:
      - "${REDIS_PORT}:6379"  # Exposing Redis on the default port 6379
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD:-defaultpassword}  # Optionally set a Redis password
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD:-defaultpassword}"]
    volumes:
      - ${REDIS_PROJ_DIR}:/data  # Persistent volume for Redis data
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 30s
